Add architecture
GrigoryKharchenko/MKK pull request #1
Opened 2022-10-13 18:47 UTC by GrigoryKharchenko

Добавил базовую архитектуру в проект

2022-10-13 19:06 UTC, GrigoryKharchenko commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.12.0'
думал что понадобится, удалил

2022-10-14 05:35 UTC, GrigoryKharchenko commented on app/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
исправил

2022-10-14 10:59 UTC, Skripchenko-Nikolai approved these changes

2022-10-14 12:28 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/di/VIewModelFactory.kt
> +package com.mkk.ru.di
Название VIew... ???

2022-10-14 12:57 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/VIewModelFactory.kt
> +package com.mkk.ru.di
исправил

2022-10-15 16:48 UTC, LuchemeteOtake requested changes

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.8.0'
зачем версию поменял?

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/build.gradle
> +        freeCompilerArgs = ['-Xjvm-default=compatibility']
что означает этот флаг?

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.2.1'
почему некоторые версии вынесены, а некоторые нет?

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/MkkApp.kt
> +}
![image](https://user-images.githubusercontent.com/6733748/195998195-8d7d091b-687a-453e-af6c-95031988870b.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/di/AppComponent.kt
> +}
![image](https://user-images.githubusercontent.com/6733748/195998207-c36b02ef-5ab4-4573-8fb2-5bb701c0c679.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/di/ViewModelFactory.kt
> +}
![image](https://user-images.githubusercontent.com/6733748/195998216-31c33fb7-35d8-449a-a0c2-42c0b494ec36.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/di/module/ActivityModule.kt
> +}
![image](https://user-images.githubusercontent.com/6733748/195998218-e149525e-36a3-4c55-871a-aa7e423caae7.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/base/BaseFragment.kt
> +}
![image](https://user-images.githubusercontent.com/6733748/195998235-6f0c2695-3c72-4df6-a2cb-20699940a33a.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/main/MainActivity.kt
> +}
![image](https://user-images.githubusercontent.com/6733748/195998263-92162e97-47a6-47f4-b03e-1571205a24c9.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on app/src/main/res/layout/activity_main.xml
> +    android:layout_height="match_parent" />
![image](https://user-images.githubusercontent.com/6733748/195998282-cd8d828d-130b-4b32-a460-9bae0324d8cc.png)

2022-10-15 16:48 UTC, LuchemeteOtake commented on build.gradle
>  }
![image](https://user-images.githubusercontent.com/6733748/195998297-ba4d2a03-a772-4016-8c81-9414ead37204.png)

2022-10-15 16:51 UTC, LuchemeteOtake requested changes

2022-10-15 16:51 UTC, LuchemeteOtake commented on app/build.gradle
> +    id 'kotlin-parcelize'
зачем этот плагин?

2022-10-15 16:51 UTC, LuchemeteOtake commented on app/build.gradle
> +    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp_version"
зачем подключены либы которые не используются?

2022-10-16 08:43 UTC, Skripi commented on app/build.gradle
> +    implementation "com.squareup.okhttp3:logging-interceptor:$okhttp_version"
Я попросил подумать и добавить зависимости, которые будут использоваться в ближайшее время

2022-10-16 09:33 UTC, GrigoryKharchenko commented on app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.8.0'
вернул обратно

2022-10-16 09:33 UTC, GrigoryKharchenko commented on app/build.gradle
> +        freeCompilerArgs = ['-Xjvm-default=compatibility']
Этот флаг нужен для исправления данной ошибки: Inheritance from an interface with '@JvmDefault' members is only allowed with -Xjvm-default option, во ViewModelFactory

2022-10-16 09:33 UTC, GrigoryKharchenko commented on app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.2.1'
Так как другие версии используются всего один раз, а я вынес те библиотеки, которые используются несколько раз

2022-10-16 09:33 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/MkkApp.kt
> +}
исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/AppComponent.kt
> +}
Исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/ViewModelFactory.kt
> +}
Исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/module/ActivityModule.kt
> +}
Исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/base/BaseFragment.kt
> +}
Исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/main/MainActivity.kt
> +}
Исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/src/main/res/layout/activity_main.xml
> +    android:layout_height="match_parent" />
Исправил

2022-10-16 09:34 UTC, GrigoryKharchenko commented on app/build.gradle
> +    id 'kotlin-parcelize'
Убрал

2022-10-16 09:35 UTC, GrigoryKharchenko commented on build.gradle
>  }
Исправил

2022-10-16 09:36 UTC, Skripi commented on app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.2.1'
обычно выносят все версии

2022-10-16 09:52 UTC, Skripi approved these changes

2022-10-16 09:54 UTC, Skripchenko-Nikolai approved these changes

2022-10-16 09:58 UTC, merged

2022-10-16 10:38 UTC, LuchemeteOtake commented on app/build.gradle
> +        freeCompilerArgs = ['-Xjvm-default=compatibility']
Ну я же не это спросил)
Флаг то что делает?

А касательно вьюмодели - а как-то кроме флага это можно поправить?

2022-10-16 10:39 UTC, LuchemeteOtake commented on app/build.gradle
> +    implementation 'androidx.core:core-ktx:1.8.0'
А зачем вернул обратно?)