Add menu screen
GrigoryKharchenko/MKK pull request #10
Opened 2022-11-07 11:47 UTC by GrigoryKharchenko

Добавил экран меню.
Экран при первом открытие
![image](https://user-images.githubusercontent.com/96061286/200302314-d07b480c-c36c-4ae3-a0e8-b972944d3ad3.png)
Экран при нажатие на кнопку Открыть смену
![image](https://user-images.githubusercontent.com/96061286/200302433-aa0172b2-9151-4a72-9f64-35165582772f.png)

2022-11-07 15:56 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/customview/CustomButton.kt
> +    context: Context, attrs: AttributeSet? = null,
attrs: AttributeSet? = null на новую строчку

2022-11-07 15:56 UTC, Skripi commented on app/src/main/res/layout/custom_button_menu.xml
> +        android:src="@drawable/ic_printer" />
Почему android:src?

2022-11-07 15:56 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/customview/CustomButton.kt
> +class CustomButton @JvmOverloads constructor(
Что за нейминг? Дай нормальное название кнопки, чтобы было понятно к чему она относится. Если я еще попрошу создать парочку кстомных кнопок, то ты их как назовешь? CustomButton1 CustomButton2 CustomButton3?

2022-11-07 15:56 UTC, Skripi commented on app/src/main/res/values/themes.xml
> +    <style name="WhiteButtonTextColorRed" parent="Widget.MaterialComponents.Button">
Так не пойдет, опять название страшное.

2022-11-07 15:56 UTC, Skripi commented on app/src/main/res/values/colors.xml
> +    <color name="faux_illuminating_emerald">#3F8499</color>
faux_illuminating_emerald - чего? А есть более понятные названия?

2022-11-07 15:56 UTC, Skripi commented on app/src/main/res/values/attrs.xml
> +        <attr name="startIconSrc" format="reference"/>
просто icon

2022-11-07 15:56 UTC, Skripi commented on app/src/main/res/layout/fragment_menu.xml
> +        android:layout_width="match_parent"
0dp

2022-11-07 15:56 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                btnGenerateReport.visibility = View.VISIBLE
И правда, зачем VIewModel?

2022-11-07 15:56 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                btnGenerateReport.visibility = View.VISIBLE
ОБработка происходит через viewModel

2022-11-08 04:59 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/customview/CustomButton.kt
> +    context: Context, attrs: AttributeSet? = null,
Исправил

2022-11-08 05:00 UTC, GrigoryKharchenko commented on app/src/main/res/layout/custom_button_menu.xml
> +        android:src="@drawable/ic_printer" />
Исправил

2022-11-08 05:00 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/customview/CustomButton.kt
> +class CustomButton @JvmOverloads constructor(
Исправил

2022-11-08 05:00 UTC, GrigoryKharchenko commented on app/src/main/res/values/themes.xml
> +    <style name="WhiteButtonTextColorRed" parent="Widget.MaterialComponents.Button">
Исправил

2022-11-08 05:01 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                btnGenerateReport.visibility = View.VISIBLE
Исправил

2022-11-08 05:01 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_menu.xml
> +        android:layout_width="match_parent"
Исправил

2022-11-08 05:01 UTC, GrigoryKharchenko commented on app/src/main/res/values/attrs.xml
> +        <attr name="startIconSrc" format="reference"/>
Исправил

2022-11-08 05:01 UTC, GrigoryKharchenko commented on app/src/main/res/values/colors.xml
> +    <color name="faux_illuminating_emerald">#3F8499</color>
Исправил

2022-11-08 07:20 UTC, LuchemeteOtake requested changes

2022-11-08 07:20 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +        viewModel.viewEffectFlow.onEach(::handleViewEffect)
тут через :: а выше два раза нет. почем?)

2022-11-08 07:20 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                binding.btnOpenShift.isVisible = btnOpenShift
with binding?

2022-11-08 07:20 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffect.kt
> +    class ChangeShift(
другие будут или так один и останется?

2022-11-08 07:20 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffect.kt
> +    class ChangeShift(
а почему не дата класс?

2022-11-08 07:20 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_menu.xml
> +        android:layout_width="match_parent"
match_parent в констрейнте

2022-11-08 11:11 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +        viewModel.viewEffectFlow.onEach(::handleViewEffect)
Обсудили

2022-11-08 11:11 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                binding.btnOpenShift.isVisible = btnOpenShift
Исправил

2022-11-08 11:11 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffect.kt
> +    class ChangeShift(
Исправил

2022-11-08 11:12 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_menu.xml
> +        android:layout_width="match_parent"
Исправил

2022-11-08 11:12 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                    btnGenerateReport.isVisible = viewEffects.btnGenerateReport
Может объединить как нибудь в ViewGroup чтобы не писать для каждого эелмента isVisible?

2022-11-08 11:14 UTC, Skripchenko-Nikolai commented on app/src/main/res/drawable/corner_custom_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
Название поменяй

2022-11-08 11:16 UTC, Skripchenko-Nikolai commented on app/src/main/res/drawable/ripple_custom_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
название

2022-11-08 11:17 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_menu.xml
> +
Мб ProgressBar навесить?

2022-11-08 15:59 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuFragment.kt
> +                    btnGenerateReport.isVisible = viewEffects.btnGenerateReport
Исправил

2022-11-08 15:59 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +        val btnSale: Boolean,
Обговорили

2022-11-08 15:59 UTC, GrigoryKharchenko commented on app/src/main/res/drawable/corner_custom_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
Исправил

2022-11-08 15:59 UTC, GrigoryKharchenko commented on app/src/main/res/drawable/ripple_custom_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
Исправил

2022-11-08 16:08 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +        val group: Boolean
group - непонятные название. Что это означает? Группа? Группа типа Boolean? Через недельку сам поймешь что означает это свойство?

2022-11-08 16:08 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +    object ShowProgressBar : MenuViewEffects()
ShowProgressBar - нет обработки даже, поэтому зачем он тут?

2022-11-08 16:08 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +    val viewEffectsFlow = _viewEffectsFlow.asSharedFlow()
val viewEffectsFlow get() =

2022-11-08 16:08 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +                    group = true
А в одну строчку не помещается?

2022-11-08 16:08 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +                    group = false
И зачем два метода, которые совершенно одинаковые? Может сделать один с параметром?

2022-11-08 16:08 UTC, Skripi commented on app/src/main/res/layout/fragment_claim_status.xml
> +        style="@style/WhiteButton.TextSize16"
Опять какой-то WhiteButton? Это реально просто белая кнопка?

2022-11-08 16:08 UTC, Skripi commented on app/src/main/res/layout/fragment_menu.xml
> +    <com.mkk.ru.presentation.customview.ButtonWithIcon
ButtonWithIcon - чего? Это понятное название? Ну назови ты эту кнопку под стиль экрана MenuButton

2022-11-08 16:08 UTC, Skripi commented on app/src/main/res/layout/fragment_menu.xml
> +        android:id="@+id/btnListChecks"
btnChecks

2022-11-08 16:08 UTC, Skripi commented on app/src/main/res/layout/fragment_menu.xml
> +        app:icon="@drawable/ic_vector"
ic_vector - что это за картинка? Что на ней нарисовано?

2022-11-08 17:57 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_claim_status.xml
> +        style="@style/WhiteButton.TextSize16"
Да просто белая кнопка с TealBasic текстом и обводкой

2022-11-08 18:02 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_menu.xml
> +        app:icon="@drawable/ic_vector"
Исправил

2022-11-08 18:08 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +                    group = true
Исправил

2022-11-08 18:08 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +    val viewEffectsFlow = _viewEffectsFlow.asSharedFlow()
Исправил

2022-11-08 18:08 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +    object ShowProgressBar : MenuViewEffects()
Исправил

2022-11-08 18:08 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +        val group: Boolean
Исправил

2022-11-09 04:16 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_claim_status.xml
> +        style="@style/WhiteButton.TextSize16"
Исправил

2022-11-09 05:50 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/customview/MenuButton.kt
> +        val text = styleAttributes.getText(R.styleable.MenuButton_android_text)
Почему текст написан в разных стилях? ТО кемел кейс, то снейк кейс

2022-11-09 05:50 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +        val groupOpenShift: Boolean
groupOpenShift = группа открытия смены? Какая группа? Что за группа? Почему boolean?
isOpenedShift

2022-11-09 05:50 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +    fun changeShift(groupOpenShift: Boolean) {
isOpenedShift

2022-11-09 05:50 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/splashscreen/SplashScreenFragment.kt
> +            addFragment<MenuFragment>(R.id.container)
почему MenuFragment открывается в SplashScreenFragment?

2022-11-09 05:50 UTC, Skripi commented on app/src/main/res/values/themes.xml
> +    <style name="OutlinedButton.TealBasic">
OutlinedTealBasicButton

2022-11-09 05:50 UTC, Skripi commented on app/src/main/res/values/themes.xml
> +    <style name="OutlinedButton.Red">
OutlinedRedButton

2022-11-09 05:50 UTC, Skripi commented on app/src/main/res/values/themes.xml
> +    <style name="OutlinedButton.Red">
И внутри этого стиля размер текста

2022-11-09 06:23 UTC, GrigoryKharchenko commented on app/src/main/res/values/themes.xml
> +    <style name="OutlinedButton.Red">
Исправил

2022-11-09 06:23 UTC, GrigoryKharchenko commented on app/src/main/res/values/themes.xml
> +    <style name="OutlinedButton.TealBasic">
Исправил

2022-11-09 06:24 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/splashscreen/SplashScreenFragment.kt
> +            addFragment<MenuFragment>(R.id.container)
Исправил

2022-11-09 06:24 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewModel.kt
> +    fun changeShift(groupOpenShift: Boolean) {
Исправил

2022-11-09 06:24 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/menu/MenuViewEffects.kt
> +        val groupOpenShift: Boolean
Исправил

2022-11-09 06:54 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/customview/MenuButton.kt
> +        val text = styleAttributes.getText(R.styleable.MenuButton_android_text)
Текст написан в разных стилях, потому что MenuButton это название файла для кастомных атрибутов, которое должно писаться в кемел кейсе, MenuButton_icon,MenuButton_android_text и так далее, это атрибуты которые пишутся через снейк кейс, так как обращение идет через MenuButton и далее студия сама генерирует название атрибутов

2022-11-09 11:07 UTC, Skripi approved these changes

2022-11-09 11:07 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/customview/MenuButton.kt
> +        val text = styleAttributes.getText(R.styleable.MenuButton_android_text)
+

2022-11-09 11:08 UTC, merged