Implement add product sreen
GrigoryKharchenko/MKK pull request #13
Opened 2022-11-15 16:06 UTC by GrigoryKharchenko

Добавил экран: Добавить товар
![image](https://user-images.githubusercontent.com/96061286/201967841-d7c0aff9-b6f7-4eb0-8905-2fb0757dd160.png)
![image](https://user-images.githubusercontent.com/96061286/201967876-2f8c11f3-851a-4cd2-900e-4226228bdda5.png)

2022-11-16 04:36 UTC, Skripi commented on app/src/main/java/com/mkk/ru/extension/FragmentTransactionExtension.kt
> +inline fun <reified F : Fragment> Fragment.addFragment(containerId: Int, backStack: String) {
backStack - это TAG

2022-11-16 05:30 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/plusproduct/AddProductViewModel.kt
> +    val typeUnitsFlow get() = _typeUnitsFlow.asStateFlow()
здесь get()

2022-11-16 05:30 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/plusproduct/AddProductViewModel.kt
> +    val validationFlow = _validationFlow.asSharedFlow()
здесь нет get()
К единому стилю

2022-11-16 05:30 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/sale/SaleFragment.kt
> +            addFragment<AddProductFragment>(R.id.container, "SaleFragment")
TAG в companion

2022-11-16 05:30 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/sale/SaleFragment.kt
> +        backSaleFragment()
зайти на экарн не успеваешь как сразу выходишь с него?

2022-11-16 05:30 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_registration_cash_box.xml
> +                android:id="@+id/tilProduct"
Что за ренейм?

2022-11-18 09:01 UTC, LuchemeteOtake requested changes

2022-11-18 09:01 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/sale/SaleFragment.kt
> +        const val TAG = "SaleFragment"
почему бы вместо тега не использовать class.simpleName, если всё равно имя класса сюда пишешь?
(не прошу тебя сразу поменять, объясни почему ты так не сделал)

2022-11-18 13:30 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/extension/FragmentTransactionExtension.kt
> +inline fun <reified F : Fragment> Fragment.addFragment(containerId: Int, backStack: String) {
Исправил

2022-11-18 13:30 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/extension/ContextExtension.kt
> +fun Context.hideKeyboard(view: View) {
Исправил

2022-11-18 13:31 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/extension/FragmentExtension.kt
> +fun Fragment.hideKeyboard() {
Исправил

2022-11-18 13:31 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/plusproduct/AddProductViewModel.kt
> +    val typeUnitsFlow get() = _typeUnitsFlow.asStateFlow()
Исправил

2022-11-18 13:31 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/plusproduct/AddProductViewModel.kt
> +    val validationFlow = _validationFlow.asSharedFlow()
Исправил

2022-11-18 13:31 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/sale/SaleFragment.kt
> +        backSaleFragment()
Исправил

2022-11-18 13:31 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_registration_cash_box.xml
> +                android:id="@+id/tilProduct"
Исправил

2022-11-19 16:06 UTC, LuchemeteOtake requested changes

2022-11-19 16:06 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/plusproduct/AddProductUiState.kt
> +    @StringRes val isVisibleCodeProductError: Int? = null,
Все поля называются isVisible, ни одно из полей не boolean

2022-11-19 16:06 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/splashscreen/SplashScreenFragment.kt
>  import com.mkk.ru.presentation.screen.registrationcashbox.RegistrationCashBoxFragment
Эт чаво за импорт?

2022-11-19 16:06 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/sale/SaleFragment.kt
> +                addFragment<AddProductFragment>(R.id.container, TAG)
@GrigoryKharchenko а расскажи как это работает?
ты передаешь AddProductFragment и тег от SaleFragment. почему?

2022-11-20 06:09 UTC, LuchemeteOtake requested changes

2022-11-20 06:09 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/plusproduct/AddProductFragment.kt
> +            tvUnits.setOnItemClickListener { _, _, position, _ ->
Это можно вынести в initBinding, кликлистнер у тебя от адаптера не зависит

2022-11-21 04:53 UTC, merged