Add splash screen
GrigoryKharchenko/MKK pull request #2
Opened 2022-10-14 10:03 UTC by GrigoryKharchenko

Добавил splash screen

2022-10-14 12:28 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/dimen.xml
> +    <dimen name="dp_40">40dp</dimen>
Нормальные названия для dp и sp

2022-10-14 12:28 UTC, Skripchenko-Nikolai commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        android:textSize="@dimen/sp_16"
А может в стили вынести чтобы не писать каждый раз android:textColor="@color/white" android:textSize="@dimen/sp_16"

2022-10-14 12:28 UTC, Skripchenko-Nikolai commented on app/src/main/res/drawable/gradient_color.xml
> +<?xml version="1.0" encoding="utf-8"?>
поменяй название файла

2022-10-14 12:54 UTC, Skripi commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        android:textSize="@dimen/sp_16"
+

2022-10-14 12:56 UTC, Skripi commented on app/src/main/res/values/strings.xml
> +    <string name="splash_screen_fragment_app_version">Version %s</string>
Мы на английском будет приложение писать?

2022-10-14 13:02 UTC, GrigoryKharchenko commented on app/src/main/res/drawable/gradient_color.xml
> +<?xml version="1.0" encoding="utf-8"?>
исправил

2022-10-14 13:09 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        android:textSize="@dimen/sp_16"
исправил

2022-10-14 13:10 UTC, GrigoryKharchenko commented on app/src/main/res/values/strings.xml
> +    <string name="splash_screen_fragment_app_version">Version %s</string>
исправил

2022-10-15 16:58 UTC, LuchemeteOtake requested changes

2022-10-15 16:58 UTC, LuchemeteOtake commented on app/build.gradle
>  plugins {
почему изменения такие же как и в первом ПРе?

2022-10-15 16:58 UTC, LuchemeteOtake commented on app/src/main/java/com/mkk/ru/presentation/screen/SplashScreenFragment.kt
> +    private val binding get() = _binding!!
зачем?

2022-10-15 16:58 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        app:layout_constraintTop_toTopOf="parent" />
что будет если телефон повернуть в лендскейп и поставить в настройках самые большие размеры шрифта и интерфейса?

2022-10-15 16:58 UTC, LuchemeteOtake commented on app/src/main/res/values/strings.xml
> +    <string name="splash_screen_fragment_title">Мобильные Кассы \n Кыргызстана</string>
зачем пробелы вокруг переноса строки?

2022-10-15 17:02 UTC, LuchemeteOtake commented on app/build.gradle
>  plugins {
и коммиты с одинаковым названием
#1
![image](https://user-images.githubusercontent.com/6733748/195998889-521f4b66-f36d-4494-a2e6-da28ec222d7c.png)
#2
![image](https://user-images.githubusercontent.com/6733748/195998901-c20ffa5b-fdad-4be5-8113-0514abfce805.png)

2022-10-16 08:40 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/SplashScreenFragment.kt
> +    private val binding get() = _binding!!
Гайды гугла)

2022-10-16 08:41 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/SplashScreenFragment.kt
> +    private val binding get() = _binding!!
И в этом классе, Гриша, чего-то не хватет, еще раз зайди в гайды гугла и посмотри чего
P.S Fragment может пережить View

2022-10-16 14:42 UTC, LuchemeteOtake requested changes

2022-10-16 14:42 UTC, LuchemeteOtake commented on build.gradle
> +    lifecycle_version = '2.4.1'
А это тут зачем и почему?

2022-10-16 14:42 UTC, LuchemeteOtake commented
Конфликты поправь

2022-10-16 15:43 UTC, GrigoryKharchenko commented on app/src/main/res/values/strings.xml
> +    <string name="splash_screen_fragment_title">Мобильные Кассы \n Кыргызстана</string>
Исправил

2022-10-16 17:26 UTC, GrigoryKharchenko commented on app/build.gradle
>  plugins {
исправил

2022-10-16 18:09 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/SplashScreenFragment.kt
> +    private val binding get() = _binding!!
исправил

2022-10-16 18:10 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        app:layout_constraintTop_toTopOf="parent" />
![Снимок](https://user-images.githubusercontent.com/96061286/196051128-7ea81281-6009-4108-9e6a-ed7e743b694c.PNG)
Будет вот так...

2022-10-17 05:24 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/di/VIewModelFactory.kt
> +}
гду пустая строка

2022-10-17 05:24 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/SplashScreenViewModel.kt
> +}
Зачем здесб {}, тебе даже Android Studio подсвечивает что они сейчас не нужны

2022-10-17 05:24 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/colors.xml
>  </resources>
Пустая строка

2022-10-17 05:24 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/dimen.xml
> +</resources>
Пустая строка

2022-10-17 05:24 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/strings.xml
>  </resources>
Пустая строка

2022-10-17 05:24 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/themes.xml
>  </resources>
Пустая строка

2022-10-17 05:30 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/SplashScreenViewModel.kt
> +}
исправил

2022-10-17 05:30 UTC, GrigoryKharchenko commented on app/src/main/res/values/colors.xml
>  </resources>
исправил

2022-10-17 05:32 UTC, GrigoryKharchenko commented on app/src/main/res/values/strings.xml
>  </resources>
исправил

2022-10-17 05:32 UTC, GrigoryKharchenko commented on app/src/main/res/values/dimen.xml
> +</resources>
исправил

2022-10-17 05:32 UTC, GrigoryKharchenko commented on app/src/main/res/values/themes.xml
>  </resources>
исправил

2022-10-17 05:32 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Так может поправить? Либо заточить ориентацию.
Возможно стоит спросить, или посмотреть в требованиях...)

2022-10-17 06:27 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_splash_screen.xml
> +        app:layout_constraintTop_toTopOf="parent" />
![Снимок](https://user-images.githubusercontent.com/96061286/196104143-175a3cb6-381a-4ec4-9704-ae802e253fa5.PNG)
Исправил

2022-10-17 06:59 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/VIewModelFactory.kt
> +}
исправил

2022-10-17 07:29 UTC, Skripchenko-Nikolai approved these changes

2022-10-17 07:29 UTC, merged