Add dialog and denial registration screen
GrigoryKharchenko/MKK pull request #8
Opened 2022-10-31 16:43 UTC by GrigoryKharchenko

Добавил диалоговое окно при успешной регистрации и экран, если отказано в регистрации

2022-10-31 16:50 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusFragment.kt
> +                    R.string.dialog_success_registration_next
Не понял. А зачем ты список Int передаешь во флоу, но не используешь его? И вообще, зачем передавать список stringResId?

2022-10-31 16:50 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/denairegistration/DenialRegistrationFragment.kt
> +class DenialRegistrationFragment : BaseFragment<DenialRegistrationViewModel>() {
onDestroyView

2022-11-01 06:40 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusFragment.kt
> +                    R.string.dialog_success_registration_next
Исправил

2022-11-01 06:40 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/denairegistration/DenialRegistrationFragment.kt
> +class DenialRegistrationFragment : BaseFragment<DenialRegistrationViewModel>() {
Исправил

2022-11-01 06:42 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/di/module/FragmentModule.kt
> +    fun bindDenialRegistrationFragment(): DenialRegistrationFragment
Rename fragment

2022-11-01 06:42 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/di/module/ViewModelModule.kt
> +    fun bindDenialRegistrationViewModel(viewModel: DenialRegistrationViewModel): ViewModel
Rename viewModel

2022-11-01 06:42 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/denairegistration/DenialRegistrationViewModel.kt
> +}
Зачем тут скобки

2022-11-01 06:42 UTC, Skripchenko-Nikolai commented on app/src/main/res/values/strings.xml
> +    <string name="denial_registration_comment_description">$s</string>
Ваууу

2022-11-01 07:09 UTC, LuchemeteOtake requested changes

2022-11-01 07:09 UTC, LuchemeteOtake commented on app/src/main/res/layout/fragment_denial_registration.xml
> +        android:layout_height="0dp"
точно 0dp?

2022-11-01 07:52 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/module/FragmentModule.kt
> +    fun bindDenialRegistrationFragment(): DenialRegistrationFragment
Исправил

2022-11-01 07:52 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/di/module/ViewModelModule.kt
> +    fun bindDenialRegistrationViewModel(viewModel: DenialRegistrationViewModel): ViewModel
Исправил

2022-11-01 07:52 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/denairegistration/DenialRegistrationViewModel.kt
> +}
Исправил

2022-11-01 07:52 UTC, GrigoryKharchenko commented on app/src/main/res/values/strings.xml
> +    <string name="denial_registration_comment_description">$s</string>
Исправил

2022-11-01 07:55 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_denial_registration.xml
> +        android:layout_height="0dp"
Исправил

2022-11-01 13:31 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusFragment.kt
> +    private fun openDenialRegistrationFragment() {
А сделай 2 функции открытия fragment-ов в 1

2022-11-01 13:31 UTC, Skripchenko-Nikolai commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusViewModel.kt
> +                _openDenialRegistrationFragment.emit(Unit)
забыл заренеймить ;)

2022-11-01 17:02 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusFragment.kt
> +    private fun openDenialRegistrationFragment() {
Добавил extension

2022-11-01 17:02 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusViewModel.kt
> +                _openDenialRegistrationFragment.emit(Unit)
Исправил

2022-11-02 02:28 UTC, Skripi commented on app/src/main/java/com/mkk/ru/extension/FragmentExtension.kt
> +inline fun <reified F : Fragment> Fragment.addFragment(containerId: Int) {
В отедельный файл вынеси: FragmentTransactionExtension

2022-11-02 02:28 UTC, Skripi commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusFragment.kt
> +            showDialogFlow.onEach {
Мне нравится практика, когда обработку получения данных из флоу выносят в отдельный функцию (если обработка занимает более двух строк)

2022-11-02 02:28 UTC, Skripi commented on app/src/main/res/layout/fragment_registration_refusal.xml
> +        <LinearLayout
Почему LinearLayout?

2022-11-02 05:05 UTC, GrigoryKharchenko commented on app/src/main/res/layout/fragment_registration_refusal.xml
> +        <LinearLayout
Потому что все элементы, располагаются вертикально и последовательно, друг за другом. LinearLayout не такой требовательный остальные layout-ы

2022-11-02 05:48 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/extension/FragmentExtension.kt
> +inline fun <reified F : Fragment> Fragment.addFragment(containerId: Int) {
Исправил

2022-11-02 05:48 UTC, GrigoryKharchenko commented on app/src/main/java/com/mkk/ru/presentation/screen/claimstatus/ClaimStatusFragment.kt
> +            showDialogFlow.onEach {
Исправил

2022-11-02 06:26 UTC, merged